@CloudTestProject_HostAddress = http://localhost:5238

GET {{CloudTestProject_HostAddress}}/users/
Accept: application/json

###

GET https://test-cloud-memoryland.azurewebsites.net/hello


###

GET https://test-cloud-memoryland.azurewebsites.net/users
Accept: application/json

###

POST https://test-cloud-memoryland.azurewebsites.net/users
Content-Type: application/json

{
  "email": "abc",
  "username": "abc"
}

